# Generated by Django 4.2.11 on 2024-05-18 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.URLField(blank=True, default=None, null=True)),
                ('title', models.CharField(max_length=250)),
                ('date', models.DateField()),
                ('gener', models.CharField(max_length=250)),
                ('rating', models.FloatField(blank=True, default=3.3, null=True)),
                ('description', models.CharField(max_length=2500)),
            ],
        ),
    ]
